# DATABASE
spring:
  application:
    name: project1
  profiles:
    include:
      - oauth
      - secrets
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate   # ?? ???(???? ?????? ??)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
          github:
            redirect-uri: http://localhost:8080/login/oauth2/code/github

file:
  upload-dir: C:/Users/Public/degree_project/certification
